# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  inputs:
    script: |
      whoami;
      sudo ls -a ~/.ssh/;
      sudo cp ~/.ssh/id_rsa /root/.ssh/;
      sudo cp ~/.ssh/id_rsa.pub /root/.ssh/;

- checkout: self
  submodules: recursive

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub C4N'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: up

